wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.5
    framework: keras
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.9.13
    start_time: 1668685076.671828
    t:
      1:
      - 2
      - 3
      - 55
      2:
      - 2
      - 3
      - 55
      3:
      - 2
      - 3
      - 8
      - 23
      - 37
      4: 3.9.13
      5: 0.13.5
      8:
      - 1
      - 5
      10:
      - 9
batch_size:
  desc: null
  value: 64
dropout:
  desc: null
  value: 0.4760287805440472
epochs:
  desc: null
  value: 74
learning_rate:
  desc: null
  value: 0.08254212516605844
size_1:
  desc: null
  value: 165
size_2:
  desc: null
  value: 118
size_3:
  desc: null
  value: 245
size_4:
  desc: null
  value: 211
size_5:
  desc: null
  value: 181
