wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.5
    framework: keras
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.9.13
    start_time: 1668674815.092663
    t:
      1:
      - 2
      - 3
      - 55
      2:
      - 2
      - 3
      - 55
      3:
      - 2
      - 3
      - 8
      - 23
      - 37
      4: 3.9.13
      5: 0.13.5
      8:
      - 1
      - 5
      10:
      - 9
batch_size:
  desc: null
  value: 64
dropout:
  desc: null
  value: 0.07282683204366418
epochs:
  desc: null
  value: 73
learning_rate:
  desc: null
  value: 0.02898961069136834
size_1:
  desc: null
  value: 216
size_2:
  desc: null
  value: 186
size_3:
  desc: null
  value: 160
size_4:
  desc: null
  value: 256
size_5:
  desc: null
  value: 93
