wandb_version: 1

batch_size:
  value: 128
dropout:
  value: 0.2103496342424
epochs:
  value: 85
learning_rate:
  value: 0.030909598866255095
size_1:
  value: 227
size_2:
  value: 132
size_3:
  value: 93
size_4:
  value: 245
size_5:
  value: 230
