wandb_version: 1

batch_size:
  value: 128
dropout:
  value: 0.5451758258538926
epochs:
  value: 36
learning_rate:
  value: 0.03166852685138684
size_1:
  value: 231
size_2:
  value: 159
size_3:
  value: 239
size_4:
  value: 163
size_5:
  value: 105
