wandb_version: 1

batch_size:
  value: 96
dropout:
  value: 0.04529475146705928
epochs:
  value: 47
learning_rate:
  value: 0.003356471814593776
size_1:
  value: 251
size_2:
  value: 190
size_3:
  value: 97
size_4:
  value: 75
size_5:
  value: 93
