wandb_version: 1

batch_size:
  value: 96
dropout:
  value: 0.3083917895100457
epochs:
  value: 73
learning_rate:
  value: 0.006716760276223044
size_1:
  value: 160
size_2:
  value: 224
size_3:
  value: 128
size_4:
  value: 114
size_5:
  value: 99
