wandb_version: 1

batch_size:
  value: 64
dropout:
  value: 0.10312612661897018
epochs:
  value: 26
learning_rate:
  value: 0.02650706633075063
size_1:
  value: 197
size_2:
  value: 191
size_3:
  value: 166
size_4:
  value: 254
size_5:
  value: 192
