wandb_version: 1

batch_size:
  value: 96
dropout:
  value: 0.34739862046850484
epochs:
  value: 64
learning_rate:
  value: 0.025871694483015597
size_1:
  value: 196
size_2:
  value: 174
size_3:
  value: 118
size_4:
  value: 104
size_5:
  value: 142
