wandb_version: 1

batch_size:
  value: 64
dropout:
  value: 0.20168919617704809
epochs:
  value: 65
learning_rate:
  value: 0.017890475346497094
size_1:
  value: 89
size_2:
  value: 143
size_3:
  value: 78
size_4:
  value: 242
size_5:
  value: 177
