wandb_version: 1

batch_size:
  value: 32
dropout:
  value: 0.365255191454728
epochs:
  value: 73
learning_rate:
  value: 0.06701301355288311
size_1:
  value: 186
size_2:
  value: 92
size_3:
  value: 155
size_4:
  value: 146
size_5:
  value: 95
