wandb_version: 1

batch_size:
  value: 32
dropout:
  value: 0.5604708892712809
epochs:
  value: 84
learning_rate:
  value: 0.07007335678285512
size_1:
  value: 65
size_2:
  value: 222
size_3:
  value: 95
size_4:
  value: 129
size_5:
  value: 155
