wandb_version: 1

batch_size:
  value: 96
dropout:
  value: 0.42032670770352903
epochs:
  value: 28
learning_rate:
  value: 0.040800780826530006
size_1:
  value: 144
size_2:
  value: 168
size_3:
  value: 232
size_4:
  value: 103
size_5:
  value: 226
