wandb_version: 1

batch_size:
  value: 64
dropout:
  value: 0.17434240555651118
epochs:
  value: 82
learning_rate:
  value: 0.0423842855540684
size_1:
  value: 145
size_2:
  value: 239
size_3:
  value: 101
size_4:
  value: 144
size_5:
  value: 131
