wandb_version: 1

batch_size:
  value: 32
dropout:
  value: 0.17796450183269555
epochs:
  value: 62
learning_rate:
  value: 0.06818902958648401
size_1:
  value: 124
size_2:
  value: 231
size_3:
  value: 205
size_4:
  value: 91
size_5:
  value: 202
