wandb_version: 1

batch_size:
  value: 32
dropout:
  value: 0.39977722371751007
epochs:
  value: 95
learning_rate:
  value: 0.05476650572814632
size_1:
  value: 147
size_2:
  value: 97
size_3:
  value: 141
size_4:
  value: 182
size_5:
  value: 203
