wandb_version: 1

batch_size:
  value: 64
dropout:
  value: 0.2855870080319566
epochs:
  value: 38
learning_rate:
  value: 0.06600126185116949
size_1:
  value: 98
size_2:
  value: 88
size_3:
  value: 173
size_4:
  value: 64
size_5:
  value: 128
