wandb_version: 1

batch_size:
  value: 64
dropout:
  value: 0.34704597407466
epochs:
  value: 69
learning_rate:
  value: 0.09857909631466892
size_1:
  value: 170
size_2:
  value: 142
size_3:
  value: 223
size_4:
  value: 84
size_5:
  value: 85
