wandb_version: 1

batch_size:
  value: 64
dropout:
  value: 0.086156657079944
epochs:
  value: 41
learning_rate:
  value: 0.03489473819128345
size_1:
  value: 100
size_2:
  value: 176
size_3:
  value: 159
size_4:
  value: 95
size_5:
  value: 236
