wandb_version: 1

batch_size:
  value: 128
dropout:
  value: 0.2499765962052932
epochs:
  value: 58
learning_rate:
  value: 0.09428231213293936
size_1:
  value: 88
size_2:
  value: 210
size_3:
  value: 109
size_4:
  value: 69
size_5:
  value: 120
