wandb_version: 1

batch_size:
  value: 64
dropout:
  value: 0.5693046314431077
epochs:
  value: 58
learning_rate:
  value: 0.08769417834192764
size_1:
  value: 250
size_2:
  value: 100
size_3:
  value: 165
size_4:
  value: 89
size_5:
  value: 189
