wandb_version: 1

batch_size:
  value: 64
dropout:
  value: 0.07282683204366418
epochs:
  value: 73
learning_rate:
  value: 0.02898961069136834
size_1:
  value: 216
size_2:
  value: 186
size_3:
  value: 160
size_4:
  value: 256
size_5:
  value: 93
