wandb_version: 1

batch_size:
  value: 96
dropout:
  value: 0.04280250214778079
epochs:
  value: 56
learning_rate:
  value: 0.07079273188227624
size_1:
  value: 204
size_2:
  value: 125
size_3:
  value: 237
size_4:
  value: 169
size_5:
  value: 104
