wandb_version: 1

batch_size:
  value: 96
dropout:
  value: 0.16328533743036736
epochs:
  value: 85
learning_rate:
  value: 0.06773749712056579
size_1:
  value: 195
size_2:
  value: 141
size_3:
  value: 189
size_4:
  value: 202
size_5:
  value: 220
