wandb_version: 1

batch_size:
  value: 32
dropout:
  value: 0.34272962801671575
epochs:
  value: 71
learning_rate:
  value: 0.06438285410521143
size_1:
  value: 241
size_2:
  value: 122
size_3:
  value: 139
size_4:
  value: 184
size_5:
  value: 176
