wandb_version: 1

batch_size:
  value: 96
dropout:
  value: 0.5545604921294505
epochs:
  value: 59
learning_rate:
  value: 0.016782199658345032
size_1:
  value: 233
size_2:
  value: 177
size_3:
  value: 111
size_4:
  value: 109
size_5:
  value: 134
