wandb_version: 1

batch_size:
  value: 64
dropout:
  value: 0.32098738139689326
epochs:
  value: 42
learning_rate:
  value: 0.002495941897440557
size_1:
  value: 107
size_2:
  value: 243
size_3:
  value: 148
size_4:
  value: 195
size_5:
  value: 84
