wandb_version: 1

batch_size:
  value: 96
dropout:
  value: 0.5812230798742433
epochs:
  value: 100
learning_rate:
  value: 0.04149486712423059
size_1:
  value: 95
size_2:
  value: 255
size_3:
  value: 102
size_4:
  value: 77
size_5:
  value: 74
