wandb_version: 1

batch_size:
  value: 64
dropout:
  value: 0.02190404688553893
epochs:
  value: 42
learning_rate:
  value: 0.05991422839373091
size_1:
  value: 231
size_2:
  value: 234
size_3:
  value: 69
size_4:
  value: 85
size_5:
  value: 121
