wandb_version: 1

batch_size:
  value: 128
dropout:
  value: 0.5834910164041057
epochs:
  value: 85
learning_rate:
  value: 0.09840564925704771
size_1:
  value: 89
size_2:
  value: 148
size_3:
  value: 95
size_4:
  value: 95
size_5:
  value: 174
