wandb_version: 1

batch_size:
  value: 128
dropout:
  value: 0.22524756172775695
epochs:
  value: 82
learning_rate:
  value: 0.04011149183896099
size_1:
  value: 93
size_2:
  value: 98
size_3:
  value: 165
size_4:
  value: 66
size_5:
  value: 67
