wandb_version: 1

batch_size:
  value: 32
dropout:
  value: 0.0835849298232263
epochs:
  value: 78
learning_rate:
  value: 0.04000494460665665
size_1:
  value: 229
size_2:
  value: 211
size_3:
  value: 231
size_4:
  value: 93
size_5:
  value: 125
