wandb_version: 1

batch_size:
  value: 128
dropout:
  value: 0.35754399583735363
epochs:
  value: 41
learning_rate:
  value: 0.07927076142201923
size_1:
  value: 69
size_2:
  value: 250
size_3:
  value: 185
size_4:
  value: 117
size_5:
  value: 192
