wandb_version: 1

batch_size:
  value: 96
dropout:
  value: 0.5220191002606285
epochs:
  value: 61
learning_rate:
  value: 0.024340252261497476
size_1:
  value: 251
size_2:
  value: 78
size_3:
  value: 99
size_4:
  value: 191
size_5:
  value: 106
