wandb_version: 1

batch_size:
  value: 32
dropout:
  value: 0.011701639443744404
epochs:
  value: 56
learning_rate:
  value: 0.033274229316110605
size_1:
  value: 77
size_2:
  value: 139
size_3:
  value: 193
size_4:
  value: 106
size_5:
  value: 73
