wandb_version: 1

batch_size:
  value: 96
dropout:
  value: 0.3307140731083716
epochs:
  value: 79
learning_rate:
  value: 0.04576342784566293
size_1:
  value: 158
size_2:
  value: 249
size_3:
  value: 146
size_4:
  value: 215
size_5:
  value: 103
