wandb_version: 1

batch_size:
  value: 128
dropout:
  value: 0.000609674866800236
epochs:
  value: 61
learning_rate:
  value: 0.0859929104405781
size_1:
  value: 174
size_2:
  value: 226
size_3:
  value: 173
size_4:
  value: 243
size_5:
  value: 226
