wandb_version: 1

batch_size:
  value: 32
dropout:
  value: 0.5845825155382478
epochs:
  value: 46
learning_rate:
  value: 0.023576029829522196
size_1:
  value: 105
size_2:
  value: 68
size_3:
  value: 194
size_4:
  value: 220
size_5:
  value: 199
