wandb_version: 1

batch_size:
  value: 96
dropout:
  value: 0.42590378461750583
epochs:
  value: 42
learning_rate:
  value: 0.03337783795922289
size_1:
  value: 101
size_2:
  value: 210
size_3:
  value: 252
size_4:
  value: 193
size_5:
  value: 161
