wandb_version: 1

batch_size:
  value: 32
dropout:
  value: 0.05508483290630215
epochs:
  value: 70
learning_rate:
  value: 0.02642320489973057
size_1:
  value: 81
size_2:
  value: 165
size_3:
  value: 74
size_4:
  value: 214
size_5:
  value: 209
