wandb_version: 1

batch_size:
  value: 96
dropout:
  value: 0.5868230657368447
epochs:
  value: 89
learning_rate:
  value: 0.02214662944736382
size_1:
  value: 91
size_2:
  value: 135
size_3:
  value: 81
size_4:
  value: 215
size_5:
  value: 193
