wandb_version: 1

batch_size:
  value: 32
dropout:
  value: 0.5377293911240312
epochs:
  value: 98
learning_rate:
  value: 0.027903247322620263
size_1:
  value: 187
size_2:
  value: 182
size_3:
  value: 254
size_4:
  value: 228
size_5:
  value: 117
