wandb_version: 1

batch_size:
  value: 32
dropout:
  value: 0.08974461757519465
epochs:
  value: 29
learning_rate:
  value: 0.011818575075673963
size_1:
  value: 228
size_2:
  value: 171
size_3:
  value: 151
size_4:
  value: 66
size_5:
  value: 105
