wandb_version: 1

batch_size:
  value: 96
dropout:
  value: 0.4401600397061575
epochs:
  value: 35
learning_rate:
  value: 0.04028859624161593
size_1:
  value: 137
size_2:
  value: 105
size_3:
  value: 186
size_4:
  value: 84
size_5:
  value: 241
