wandb_version: 1

batch_size:
  value: 96
dropout:
  value: 0.273549305119958
epochs:
  value: 37
learning_rate:
  value: 0.025547277902580125
size_1:
  value: 120
size_2:
  value: 234
size_3:
  value: 118
size_4:
  value: 235
size_5:
  value: 219
