wandb_version: 1

batch_size:
  value: 32
dropout:
  value: 0.37581410369114016
epochs:
  value: 59
learning_rate:
  value: 0.08016755803866113
size_1:
  value: 219
size_2:
  value: 144
size_3:
  value: 236
size_4:
  value: 191
size_5:
  value: 150
