wandb_version: 1

batch_size:
  value: 96
dropout:
  value: 0.5914342379408405
epochs:
  value: 54
learning_rate:
  value: 0.09363291577601109
size_1:
  value: 187
size_2:
  value: 116
size_3:
  value: 255
size_4:
  value: 155
size_5:
  value: 143
