wandb_version: 1

batch_size:
  value: 96
dropout:
  value: 0.09041501415347132
epochs:
  value: 47
learning_rate:
  value: 0.04382821314990331
size_1:
  value: 249
size_2:
  value: 127
size_3:
  value: 128
size_4:
  value: 209
size_5:
  value: 196
