wandb_version: 1

batch_size:
  value: 64
dropout:
  value: 0.11628158891999102
epochs:
  value: 96
learning_rate:
  value: 0.031323948091782405
size_1:
  value: 160
size_2:
  value: 88
size_3:
  value: 114
size_4:
  value: 176
size_5:
  value: 71
