wandb_version: 1

batch_size:
  value: 64
dropout:
  value: 0.2067048023354709
epochs:
  value: 88
learning_rate:
  value: 0.01879658385488932
size_1:
  value: 75
size_2:
  value: 101
size_3:
  value: 249
size_4:
  value: 154
size_5:
  value: 126
