wandb_version: 1

batch_size:
  value: 32
dropout:
  value: 0.4863544717084537
epochs:
  value: 70
learning_rate:
  value: 0.02311169692465405
size_1:
  value: 86
size_2:
  value: 253
size_3:
  value: 75
size_4:
  value: 171
size_5:
  value: 111
