wandb_version: 1

batch_size:
  value: 96
dropout:
  value: 0.2638143115360249
epochs:
  value: 30
learning_rate:
  value: 0.008296736469872867
size_1:
  value: 201
size_2:
  value: 103
size_3:
  value: 108
size_4:
  value: 160
size_5:
  value: 238
