wandb_version: 1

batch_size:
  value: 128
dropout:
  value: 0.2849293308111463
epochs:
  value: 51
learning_rate:
  value: 0.04183955845427402
size_1:
  value: 183
size_2:
  value: 148
size_3:
  value: 230
size_4:
  value: 232
size_5:
  value: 130
