wandb_version: 1

batch_size:
  value: 96
dropout:
  value: 0.28355922137113343
epochs:
  value: 52
learning_rate:
  value: 0.03139889251054464
size_1:
  value: 231
size_2:
  value: 227
size_3:
  value: 243
size_4:
  value: 252
size_5:
  value: 227
