wandb_version: 1

batch_size:
  value: 32
dropout:
  value: 0.2654027164284289
epochs:
  value: 81
learning_rate:
  value: 0.014723858662924572
size_1:
  value: 205
size_2:
  value: 168
size_3:
  value: 229
size_4:
  value: 145
size_5:
  value: 166
