wandb_version: 1

batch_size:
  value: 96
dropout:
  value: 0.10478643834684956
epochs:
  value: 75
learning_rate:
  value: 0.08862112873497471
size_1:
  value: 79
size_2:
  value: 90
size_3:
  value: 160
size_4:
  value: 106
size_5:
  value: 85
