wandb_version: 1

batch_size:
  value: 32
dropout:
  value: 0.002127436105632019
epochs:
  value: 26
learning_rate:
  value: 0.05663308069924555
size_1:
  value: 118
size_2:
  value: 256
size_3:
  value: 225
size_4:
  value: 112
size_5:
  value: 140
