wandb_version: 1

batch_size:
  value: 64
dropout:
  value: 0.21157810749210929
epochs:
  value: 68
learning_rate:
  value: 0.04839842605621058
size_1:
  value: 238
size_2:
  value: 182
size_3:
  value: 164
size_4:
  value: 85
size_5:
  value: 107
