wandb_version: 1

batch_size:
  value: 32
dropout:
  value: 0.05970213291968115
epochs:
  value: 37
learning_rate:
  value: 0.008386209570072833
size_1:
  value: 223
size_2:
  value: 79
size_3:
  value: 137
size_4:
  value: 75
size_5:
  value: 193
