wandb_version: 1

batch_size:
  value: 64
dropout:
  value: 0.4482527606117052
epochs:
  value: 50
learning_rate:
  value: 0.03877381155462534
size_1:
  value: 110
size_2:
  value: 138
size_3:
  value: 117
size_4:
  value: 104
size_5:
  value: 157
