wandb_version: 1

batch_size:
  value: 128
dropout:
  value: 0.12420740320957148
epochs:
  value: 46
learning_rate:
  value: 0.027136279048544723
size_1:
  value: 122
size_2:
  value: 207
size_3:
  value: 90
size_4:
  value: 230
size_5:
  value: 211
