wandb_version: 1

batch_size:
  value: 128
dropout:
  value: 0.5042283640882296
epochs:
  value: 79
learning_rate:
  value: 0.018421763085950827
size_1:
  value: 202
size_2:
  value: 81
size_3:
  value: 101
size_4:
  value: 210
size_5:
  value: 151
