wandb_version: 1

batch_size:
  value: 96
dropout:
  value: 0.5583625649061845
epochs:
  value: 27
learning_rate:
  value: 0.06481076138903338
size_1:
  value: 97
size_2:
  value: 64
size_3:
  value: 163
size_4:
  value: 195
size_5:
  value: 196
