wandb_version: 1

batch_size:
  value: 128
dropout:
  value: 0.08862254209687563
epochs:
  value: 73
learning_rate:
  value: 0.023359646162419947
size_1:
  value: 196
size_2:
  value: 160
size_3:
  value: 248
size_4:
  value: 76
size_5:
  value: 141
