wandb_version: 1

batch_size:
  value: 32
dropout:
  value: 0.09031752981973476
epochs:
  value: 23
learning_rate:
  value: 0.08654921473494495
size_1:
  value: 128
size_2:
  value: 141
size_3:
  value: 127
size_4:
  value: 158
size_5:
  value: 77
