wandb_version: 1

batch_size:
  value: 128
dropout:
  value: 0.118381248201942
epochs:
  value: 81
learning_rate:
  value: 0.0050481705620421535
size_1:
  value: 84
size_2:
  value: 200
size_3:
  value: 120
size_4:
  value: 126
size_5:
  value: 181
