wandb_version: 1

batch_size:
  value: 128
dropout:
  value: 0.4967533856716427
epochs:
  value: 73
learning_rate:
  value: 0.05687705220970068
size_1:
  value: 236
size_2:
  value: 244
size_3:
  value: 139
size_4:
  value: 100
size_5:
  value: 154
