wandb_version: 1

batch_size:
  value: 64
dropout:
  value: 0.015001197833720824
epochs:
  value: 36
learning_rate:
  value: 0.05967141778427973
size_1:
  value: 255
size_2:
  value: 197
size_3:
  value: 163
size_4:
  value: 102
size_5:
  value: 169
