wandb_version: 1

batch_size:
  value: 64
dropout:
  value: 0.0704639985750154
epochs:
  value: 96
learning_rate:
  value: 0.02418599682898961
size_1:
  value: 249
size_2:
  value: 156
size_3:
  value: 66
size_4:
  value: 162
size_5:
  value: 77
