wandb_version: 1

batch_size:
  value: 32
dropout:
  value: 0.3444531535591676
epochs:
  value: 31
learning_rate:
  value: 0.013625077064741998
size_1:
  value: 191
size_2:
  value: 114
size_3:
  value: 255
size_4:
  value: 107
size_5:
  value: 219
