wandb_version: 1

batch_size:
  value: 96
dropout:
  value: 0.5555104027669971
epochs:
  value: 53
learning_rate:
  value: 0.02159348914274155
size_1:
  value: 190
size_2:
  value: 72
size_3:
  value: 214
size_4:
  value: 241
size_5:
  value: 177
