wandb_version: 1

batch_size:
  value: 64
dropout:
  value: 0.4760287805440472
epochs:
  value: 74
learning_rate:
  value: 0.08254212516605844
size_1:
  value: 165
size_2:
  value: 118
size_3:
  value: 245
size_4:
  value: 211
size_5:
  value: 181
