wandb_version: 1

batch_size:
  value: 96
dropout:
  value: 0.06185011529123641
epochs:
  value: 83
learning_rate:
  value: 0.017296500206987264
size_1:
  value: 85
size_2:
  value: 107
size_3:
  value: 160
size_4:
  value: 189
size_5:
  value: 185
