wandb_version: 1

batch_size:
  value: 64
dropout:
  value: 0.3849754389300818
epochs:
  value: 33
learning_rate:
  value: 0.0691694766150495
size_1:
  value: 179
size_2:
  value: 93
size_3:
  value: 253
size_4:
  value: 221
size_5:
  value: 195
