wandb_version: 1

batch_size:
  value: 32
dropout:
  value: 0.4717300710963443
epochs:
  value: 65
learning_rate:
  value: 0.08880065492073318
size_1:
  value: 133
size_2:
  value: 162
size_3:
  value: 148
size_4:
  value: 136
size_5:
  value: 126
