wandb_version: 1

batch_size:
  value: 128
dropout:
  value: 0.5534508423315737
epochs:
  value: 80
learning_rate:
  value: 0.05727721407897723
size_1:
  value: 96
size_2:
  value: 84
size_3:
  value: 162
size_4:
  value: 221
size_5:
  value: 201
