wandb_version: 1

batch_size:
  value: 64
dropout:
  value: 0.4746239890243623
epochs:
  value: 45
learning_rate:
  value: 0.027405920688870468
size_1:
  value: 103
size_2:
  value: 183
size_3:
  value: 75
size_4:
  value: 117
size_5:
  value: 144
