wandb_version: 1

batch_size:
  value: 96
dropout:
  value: 0.1720521632597998
epochs:
  value: 73
learning_rate:
  value: 0.012748500055910683
size_1:
  value: 248
size_2:
  value: 70
size_3:
  value: 187
size_4:
  value: 243
size_5:
  value: 248
