wandb_version: 1

batch_size:
  value: 32
dropout:
  value: 0.33916149514312827
epochs:
  value: 87
learning_rate:
  value: 0.037370943412616334
size_1:
  value: 193
size_2:
  value: 97
size_3:
  value: 202
size_4:
  value: 67
size_5:
  value: 209
