wandb_version: 1

batch_size:
  value: 32
dropout:
  value: 0.2664278885271979
epochs:
  value: 90
learning_rate:
  value: 0.0858561785095313
size_1:
  value: 194
size_2:
  value: 140
size_3:
  value: 221
size_4:
  value: 66
size_5:
  value: 119
