wandb_version: 1

batch_size:
  value: 128
dropout:
  value: 0.12080202340382018
epochs:
  value: 67
learning_rate:
  value: 0.09836440383578782
size_1:
  value: 78
size_2:
  value: 71
size_3:
  value: 246
size_4:
  value: 105
size_5:
  value: 132
