wandb_version: 1

batch_size:
  value: 32
dropout:
  value: 0.4529453576942054
epochs:
  value: 58
learning_rate:
  value: 0.05375889640969589
size_1:
  value: 91
size_2:
  value: 144
size_3:
  value: 251
size_4:
  value: 237
size_5:
  value: 135
