wandb_version: 1

batch_size:
  value: 64
dropout:
  value: 0.5834897404654544
epochs:
  value: 65
learning_rate:
  value: 0.005478745553983578
size_1:
  value: 187
size_2:
  value: 158
size_3:
  value: 175
size_4:
  value: 107
size_5:
  value: 79
