wandb_version: 1

batch_size:
  value: 32
dropout:
  value: 0.5985208601091424
epochs:
  value: 92
learning_rate:
  value: 0.059768440183992105
size_1:
  value: 200
size_2:
  value: 252
size_3:
  value: 202
size_4:
  value: 228
size_5:
  value: 127
