wandb_version: 1

batch_size:
  value: 96
dropout:
  value: 0.15787859630136394
epochs:
  value: 82
learning_rate:
  value: 0.051771029535170314
size_1:
  value: 136
size_2:
  value: 254
size_3:
  value: 204
size_4:
  value: 162
size_5:
  value: 222
