wandb_version: 1

batch_size:
  value: 128
dropout:
  value: 0.05787123878835984
epochs:
  value: 21
learning_rate:
  value: 0.04809218422029792
size_1:
  value: 218
size_2:
  value: 152
size_3:
  value: 68
size_4:
  value: 190
size_5:
  value: 191
