wandb_version: 1

batch_size:
  value: 96
dropout:
  value: 0.23416011403306164
epochs:
  value: 70
learning_rate:
  value: 0.012840936641902724
size_1:
  value: 111
size_2:
  value: 163
size_3:
  value: 90
size_4:
  value: 142
size_5:
  value: 245
