wandb_version: 1

batch_size:
  value: 32
dropout:
  value: 0.5443442689110046
epochs:
  value: 97
learning_rate:
  value: 0.031646171209604335
size_1:
  value: 69
size_2:
  value: 236
size_3:
  value: 184
size_4:
  value: 178
size_5:
  value: 90
