wandb_version: 1

batch_size:
  value: 32
dropout:
  value: 0.26232693260041157
epochs:
  value: 28
learning_rate:
  value: 0.05257944562964888
size_1:
  value: 146
size_2:
  value: 149
size_3:
  value: 176
size_4:
  value: 161
size_5:
  value: 156
