wandb_version: 1

batch_size:
  value: 64
dropout:
  value: 0.07107571570470562
epochs:
  value: 84
learning_rate:
  value: 0.01993060767310169
size_1:
  value: 168
size_2:
  value: 85
size_3:
  value: 115
size_4:
  value: 186
size_5:
  value: 132
