wandb_version: 1

batch_size:
  value: 32
dropout:
  value: 0.3506272523405629
epochs:
  value: 28
learning_rate:
  value: 0.09107863981157596
size_1:
  value: 195
size_2:
  value: 117
size_3:
  value: 92
size_4:
  value: 225
size_5:
  value: 170
