wandb_version: 1

batch_size:
  value: 64
dropout:
  value: 0.1490384741334227
epochs:
  value: 88
learning_rate:
  value: 0.07895856205161754
size_1:
  value: 93
size_2:
  value: 164
size_3:
  value: 224
size_4:
  value: 224
size_5:
  value: 85
