wandb_version: 1

batch_size:
  value: 128
dropout:
  value: 0.27521246552520706
epochs:
  value: 85
learning_rate:
  value: 0.048190637475311576
size_1:
  value: 117
size_2:
  value: 175
size_3:
  value: 103
size_4:
  value: 98
size_5:
  value: 181
