wandb_version: 1

batch_size:
  value: 32
dropout:
  value: 0.23447781939755408
epochs:
  value: 24
learning_rate:
  value: 0.012080834786551533
size_1:
  value: 171
size_2:
  value: 116
size_3:
  value: 243
size_4:
  value: 209
size_5:
  value: 156
