wandb_version: 1

batch_size:
  value: 96
dropout:
  value: 0.33557457802510576
epochs:
  value: 99
learning_rate:
  value: 0.02898099683935067
size_1:
  value: 125
size_2:
  value: 226
size_3:
  value: 185
size_4:
  value: 198
size_5:
  value: 156
