wandb_version: 1

batch_size:
  value: 96
dropout:
  value: 0.1352782144546685
epochs:
  value: 39
learning_rate:
  value: 0.08870595749936189
size_1:
  value: 196
size_2:
  value: 169
size_3:
  value: 177
size_4:
  value: 143
size_5:
  value: 211
