wandb_version: 1

batch_size:
  value: 32
dropout:
  value: 0.04339143803129753
epochs:
  value: 91
learning_rate:
  value: 0.0007199398693535475
size_1:
  value: 107
size_2:
  value: 137
size_3:
  value: 119
size_4:
  value: 83
size_5:
  value: 225
