wandb_version: 1

batch_size:
  value: 128
dropout:
  value: 0.08079355055726449
epochs:
  value: 32
learning_rate:
  value: 0.06476096334994773
size_1:
  value: 171
size_2:
  value: 243
size_3:
  value: 254
size_4:
  value: 223
size_5:
  value: 76
