wandb_version: 1

batch_size:
  value: 32
dropout:
  value: 0.5100580029396404
epochs:
  value: 74
learning_rate:
  value: 0.07783788491965006
size_1:
  value: 138
size_2:
  value: 84
size_3:
  value: 135
size_4:
  value: 145
size_5:
  value: 225
