wandb_version: 1

batch_size:
  value: 64
dropout:
  value: 0.5341539209040456
epochs:
  value: 42
learning_rate:
  value: 0.015921515805084798
size_1:
  value: 189
size_2:
  value: 137
size_3:
  value: 120
size_4:
  value: 117
size_5:
  value: 189
