wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.5
    framework: keras
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.9.13
    start_time: 1668787058.917761
    t:
      1:
      - 2
      - 3
      - 55
      2:
      - 2
      - 3
      - 55
      3:
      - 2
      - 3
      - 8
      - 23
      - 37
      4: 3.9.13
      5: 0.13.5
      8:
      - 1
      - 5
      10:
      - 9
batch_size:
  desc: null
  value: 128
dropout:
  desc: null
  value: 0.4789036025147468
epochs:
  desc: null
  value: 57
learning_rate:
  desc: null
  value: 0.06426150614583769
size_1:
  desc: null
  value: 103
size_2:
  desc: null
  value: 192
size_3:
  desc: null
  value: 86
size_4:
  desc: null
  value: 171
size_5:
  desc: null
  value: 138
