wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.5
    framework: keras
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.9.13
    start_time: 1668781252.322775
    t:
      1:
      - 2
      - 3
      - 55
      2:
      - 2
      - 3
      - 55
      3:
      - 2
      - 3
      - 8
      - 23
      - 37
      4: 3.9.13
      5: 0.13.5
      8:
      - 1
      - 5
      10:
      - 9
batch_size:
  desc: null
  value: 32
dropout:
  desc: null
  value: 0.5351904926638938
epochs:
  desc: null
  value: 45
learning_rate:
  desc: null
  value: 0.05866384491406445
size_1:
  desc: null
  value: 252
size_2:
  desc: null
  value: 65
size_3:
  desc: null
  value: 192
size_4:
  desc: null
  value: 238
size_5:
  desc: null
  value: 175
