wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.5
    framework: keras
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.9.13
    start_time: 1668789469.876033
    t:
      1:
      - 2
      - 3
      - 55
      2:
      - 2
      - 3
      - 55
      3:
      - 2
      - 3
      - 8
      - 23
      - 37
      4: 3.9.13
      5: 0.13.5
      8:
      - 1
      - 5
      10:
      - 9
batch_size:
  desc: null
  value: 64
dropout:
  desc: null
  value: 0.3926357242678766
epochs:
  desc: null
  value: 99
learning_rate:
  desc: null
  value: 0.05184075919783803
size_1:
  desc: null
  value: 151
size_2:
  desc: null
  value: 104
size_3:
  desc: null
  value: 215
size_4:
  desc: null
  value: 201
size_5:
  desc: null
  value: 202
