wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.5
    framework: keras
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.9.13
    start_time: 1668684603.120638
    t:
      1:
      - 2
      - 3
      - 55
      2:
      - 2
      - 3
      - 55
      3:
      - 2
      - 3
      - 8
      - 23
      - 37
      4: 3.9.13
      5: 0.13.5
      8:
      - 1
      - 5
      10:
      - 9
batch_size:
  desc: null
  value: 64
dropout:
  desc: null
  value: 0.5341539209040456
epochs:
  desc: null
  value: 42
learning_rate:
  desc: null
  value: 0.015921515805084798
size_1:
  desc: null
  value: 189
size_2:
  desc: null
  value: 137
size_3:
  desc: null
  value: 120
size_4:
  desc: null
  value: 117
size_5:
  desc: null
  value: 189
