wandb_version: 1

batch_size:
  value: 32
dropout:
  value: 0.06747318842269497
epochs:
  value: 95
learning_rate:
  value: 0.095767106475226
size_1:
  value: 225
size_2:
  value: 129
size_3:
  value: 215
size_4:
  value: 102
size_5:
  value: 210
