wandb_version: 1

batch_size:
  value: 32
dropout:
  value: 0.04498864378057694
epochs:
  value: 66
learning_rate:
  value: 0.04267475985479122
size_1:
  value: 128
size_2:
  value: 187
size_3:
  value: 93
size_4:
  value: 65
size_5:
  value: 249
