wandb_version: 1

batch_size:
  value: 32
dropout:
  value: 0.05992285898358826
epochs:
  value: 36
learning_rate:
  value: 0.022605799200762045
size_1:
  value: 181
size_2:
  value: 245
size_3:
  value: 158
size_4:
  value: 222
size_5:
  value: 222
