wandb_version: 1

batch_size:
  value: 128
dropout:
  value: 0.21657287569923547
epochs:
  value: 50
learning_rate:
  value: 0.05380103656005223
size_1:
  value: 187
size_2:
  value: 181
size_3:
  value: 249
size_4:
  value: 100
size_5:
  value: 249
