wandb_version: 1

batch_size:
  value: 32
dropout:
  value: 0.5036914126843215
epochs:
  value: 83
learning_rate:
  value: 0.018141304045154884
size_1:
  value: 220
size_2:
  value: 229
size_3:
  value: 89
size_4:
  value: 137
size_5:
  value: 66
