wandb_version: 1

batch_size:
  value: 64
dropout:
  value: 0.2150990638020296
epochs:
  value: 66
learning_rate:
  value: 0.024082357332360072
size_1:
  value: 198
size_2:
  value: 143
size_3:
  value: 68
size_4:
  value: 254
size_5:
  value: 98
