wandb_version: 1

batch_size:
  value: 64
dropout:
  value: 0.2834186136270899
epochs:
  value: 38
learning_rate:
  value: 0.08778625412096079
size_1:
  value: 190
size_2:
  value: 198
size_3:
  value: 182
size_4:
  value: 64
size_5:
  value: 213
