wandb_version: 1

batch_size:
  value: 64
dropout:
  value: 0.5818346992650782
epochs:
  value: 92
learning_rate:
  value: 0.040656842978008395
size_1:
  value: 69
size_2:
  value: 187
size_3:
  value: 210
size_4:
  value: 174
size_5:
  value: 86
