wandb_version: 1

batch_size:
  value: 64
dropout:
  value: 0.21549509663716773
epochs:
  value: 35
learning_rate:
  value: 0.0778827484052459
size_1:
  value: 70
size_2:
  value: 195
size_3:
  value: 192
size_4:
  value: 191
size_5:
  value: 173
