wandb_version: 1

batch_size:
  value: 128
dropout:
  value: 0.45823779839898743
epochs:
  value: 24
learning_rate:
  value: 0.003132533453098041
size_1:
  value: 223
size_2:
  value: 209
size_3:
  value: 81
size_4:
  value: 221
size_5:
  value: 255
