wandb_version: 1

batch_size:
  value: 96
dropout:
  value: 0.03441949713983043
epochs:
  value: 50
learning_rate:
  value: 0.02451161819510761
size_1:
  value: 79
size_2:
  value: 136
size_3:
  value: 110
size_4:
  value: 252
size_5:
  value: 191
