wandb_version: 1

batch_size:
  value: 96
dropout:
  value: 0.47588227533326255
epochs:
  value: 53
learning_rate:
  value: 0.048648499613182045
size_1:
  value: 89
size_2:
  value: 116
size_3:
  value: 227
size_4:
  value: 242
size_5:
  value: 142
