wandb_version: 1

batch_size:
  value: 64
dropout:
  value: 0.3926357242678766
epochs:
  value: 99
learning_rate:
  value: 0.05184075919783803
size_1:
  value: 151
size_2:
  value: 104
size_3:
  value: 215
size_4:
  value: 201
size_5:
  value: 202
