wandb_version: 1

batch_size:
  value: 32
dropout:
  value: 0.5661606632757246
epochs:
  value: 74
learning_rate:
  value: 0.0931845757339709
size_1:
  value: 111
size_2:
  value: 153
size_3:
  value: 145
size_4:
  value: 230
size_5:
  value: 209
