wandb_version: 1

batch_size:
  value: 64
dropout:
  value: 0.5401597513579024
epochs:
  value: 58
learning_rate:
  value: 0.09985700045513544
size_1:
  value: 234
size_2:
  value: 186
size_3:
  value: 68
size_4:
  value: 188
size_5:
  value: 86
