wandb_version: 1

batch_size:
  value: 96
dropout:
  value: 0.3209144299467145
epochs:
  value: 83
learning_rate:
  value: 0.04462486062042571
size_1:
  value: 216
size_2:
  value: 256
size_3:
  value: 248
size_4:
  value: 78
size_5:
  value: 104
