wandb_version: 1

batch_size:
  value: 128
dropout:
  value: 0.5694649980998371
epochs:
  value: 82
learning_rate:
  value: 0.03297842922838725
size_1:
  value: 183
size_2:
  value: 76
size_3:
  value: 119
size_4:
  value: 100
size_5:
  value: 92
