wandb_version: 1

batch_size:
  value: 128
dropout:
  value: 0.012085155391357547
epochs:
  value: 69
learning_rate:
  value: 0.0702146982943237
size_1:
  value: 108
size_2:
  value: 147
size_3:
  value: 152
size_4:
  value: 197
size_5:
  value: 126
