wandb_version: 1

batch_size:
  value: 128
dropout:
  value: 0.15468454318581695
epochs:
  value: 36
learning_rate:
  value: 0.04808049264444447
size_1:
  value: 157
size_2:
  value: 163
size_3:
  value: 72
size_4:
  value: 204
size_5:
  value: 209
