wandb_version: 1

batch_size:
  value: 64
dropout:
  value: 0.1526554187878432
epochs:
  value: 92
learning_rate:
  value: 0.08752965316183127
size_1:
  value: 127
size_2:
  value: 115
size_3:
  value: 214
size_4:
  value: 175
size_5:
  value: 198
