wandb_version: 1

batch_size:
  value: 64
dropout:
  value: 0.23590527677156423
epochs:
  value: 94
learning_rate:
  value: 0.010745288424054512
size_1:
  value: 163
size_2:
  value: 71
size_3:
  value: 113
size_4:
  value: 244
size_5:
  value: 213
