wandb_version: 1

batch_size:
  value: 64
dropout:
  value: 0.5426051846986268
epochs:
  value: 78
learning_rate:
  value: 0.048422365560993136
size_1:
  value: 97
size_2:
  value: 86
size_3:
  value: 188
size_4:
  value: 82
size_5:
  value: 103
