wandb_version: 1

batch_size:
  value: 128
dropout:
  value: 0.3326940158117588
epochs:
  value: 72
learning_rate:
  value: 0.06739888327067742
size_1:
  value: 254
size_2:
  value: 243
size_3:
  value: 235
size_4:
  value: 135
size_5:
  value: 236
