wandb_version: 1

batch_size:
  value: 64
dropout:
  value: 0.24235138748376336
epochs:
  value: 99
learning_rate:
  value: 0.04847993876664633
size_1:
  value: 191
size_2:
  value: 220
size_3:
  value: 145
size_4:
  value: 255
size_5:
  value: 186
