wandb_version: 1

batch_size:
  value: 32
dropout:
  value: 0.4685677516522509
epochs:
  value: 65
learning_rate:
  value: 0.062167063579884656
size_1:
  value: 167
size_2:
  value: 255
size_3:
  value: 76
size_4:
  value: 93
size_5:
  value: 176
