wandb_version: 1

batch_size:
  value: 32
dropout:
  value: 0.5351904926638938
epochs:
  value: 45
learning_rate:
  value: 0.05866384491406445
size_1:
  value: 252
size_2:
  value: 65
size_3:
  value: 192
size_4:
  value: 238
size_5:
  value: 175
