wandb_version: 1

batch_size:
  value: 96
dropout:
  value: 0.1576223949775966
epochs:
  value: 37
learning_rate:
  value: 0.03938954339049375
size_1:
  value: 148
size_2:
  value: 75
size_3:
  value: 204
size_4:
  value: 220
size_5:
  value: 170
