wandb_version: 1

batch_size:
  value: 32
dropout:
  value: 0.3904151216922881
epochs:
  value: 66
learning_rate:
  value: 0.09477430098425982
size_1:
  value: 232
size_2:
  value: 150
size_3:
  value: 96
size_4:
  value: 143
size_5:
  value: 255
