wandb_version: 1

batch_size:
  value: 32
dropout:
  value: 0.4060593649425672
epochs:
  value: 75
learning_rate:
  value: 0.07690561124934722
size_1:
  value: 253
size_2:
  value: 166
size_3:
  value: 233
size_4:
  value: 230
size_5:
  value: 182
