wandb_version: 1

batch_size:
  value: 64
dropout:
  value: 0.11396113491891556
epochs:
  value: 60
learning_rate:
  value: 0.08764238006968646
size_1:
  value: 205
size_2:
  value: 249
size_3:
  value: 68
size_4:
  value: 180
size_5:
  value: 247
