wandb_version: 1

batch_size:
  value: 32
dropout:
  value: 0.3117500134534999
epochs:
  value: 56
learning_rate:
  value: 0.09304974678359436
size_1:
  value: 200
size_2:
  value: 219
size_3:
  value: 114
size_4:
  value: 180
size_5:
  value: 167
