wandb_version: 1

batch_size:
  value: 32
dropout:
  value: 0.27887123976407213
epochs:
  value: 64
learning_rate:
  value: 0.08969830226094197
size_1:
  value: 226
size_2:
  value: 64
size_3:
  value: 148
size_4:
  value: 214
size_5:
  value: 132
