wandb_version: 1

batch_size:
  value: 64
dropout:
  value: 0.5153252837029537
epochs:
  value: 85
learning_rate:
  value: 0.06753061409635364
size_1:
  value: 66
size_2:
  value: 209
size_3:
  value: 176
size_4:
  value: 242
size_5:
  value: 109
