wandb_version: 1

batch_size:
  value: 96
dropout:
  value: 0.5709814724183551
epochs:
  value: 45
learning_rate:
  value: 0.05909337755842904
size_1:
  value: 194
size_2:
  value: 129
size_3:
  value: 256
size_4:
  value: 162
size_5:
  value: 145
