wandb_version: 1

batch_size:
  value: 64
dropout:
  value: 0.17840494667640008
epochs:
  value: 63
learning_rate:
  value: 0.024346964440533636
size_1:
  value: 196
size_2:
  value: 129
size_3:
  value: 102
size_4:
  value: 199
size_5:
  value: 184
