wandb_version: 1

batch_size:
  value: 32
dropout:
  value: 0.31176505998917237
epochs:
  value: 45
learning_rate:
  value: 0.06406280621864208
size_1:
  value: 245
size_2:
  value: 92
size_3:
  value: 198
size_4:
  value: 76
size_5:
  value: 238
