wandb_version: 1

batch_size:
  value: 128
dropout:
  value: 0.4668778588604029
epochs:
  value: 31
learning_rate:
  value: 0.08933275602202363
size_1:
  value: 94
size_2:
  value: 75
size_3:
  value: 98
size_4:
  value: 161
size_5:
  value: 254
