wandb_version: 1

batch_size:
  value: 64
dropout:
  value: 0.24807970995362072
epochs:
  value: 99
learning_rate:
  value: 0.06125697879658966
size_1:
  value: 217
size_2:
  value: 254
size_3:
  value: 81
size_4:
  value: 92
size_5:
  value: 241
