wandb_version: 1

batch_size:
  value: 128
dropout:
  value: 0.47652867489961814
epochs:
  value: 100
learning_rate:
  value: 0.08638326346185606
size_1:
  value: 99
size_2:
  value: 186
size_3:
  value: 239
size_4:
  value: 228
size_5:
  value: 65
