wandb_version: 1

batch_size:
  value: 128
dropout:
  value: 0.4153513634425426
epochs:
  value: 43
learning_rate:
  value: 0.08924769873611044
size_1:
  value: 82
size_2:
  value: 240
size_3:
  value: 91
size_4:
  value: 209
size_5:
  value: 230
