wandb_version: 1

batch_size:
  value: 96
dropout:
  value: 0.4277076730587929
epochs:
  value: 78
learning_rate:
  value: 0.06256780491314584
size_1:
  value: 140
size_2:
  value: 129
size_3:
  value: 79
size_4:
  value: 99
size_5:
  value: 94
