wandb_version: 1

batch_size:
  value: 96
dropout:
  value: 0.25040541903851843
epochs:
  value: 36
learning_rate:
  value: 0.08150913692808802
size_1:
  value: 147
size_2:
  value: 95
size_3:
  value: 211
size_4:
  value: 135
size_5:
  value: 254
