wandb_version: 1

batch_size:
  value: 64
dropout:
  value: 0.5244392171971292
epochs:
  value: 40
learning_rate:
  value: 0.03578200146392744
size_1:
  value: 94
size_2:
  value: 107
size_3:
  value: 133
size_4:
  value: 102
size_5:
  value: 224
