wandb_version: 1

batch_size:
  value: 64
dropout:
  value: 0.25198327632875084
epochs:
  value: 66
learning_rate:
  value: 0.06222180068151413
size_1:
  value: 215
size_2:
  value: 195
size_3:
  value: 243
size_4:
  value: 203
size_5:
  value: 140
