wandb_version: 1

batch_size:
  value: 64
dropout:
  value: 0.005047924782384361
epochs:
  value: 33
learning_rate:
  value: 0.06590238019461697
size_1:
  value: 226
size_2:
  value: 181
size_3:
  value: 191
size_4:
  value: 197
size_5:
  value: 88
