wandb_version: 1

batch_size:
  value: 64
dropout:
  value: 0.19074744742961056
epochs:
  value: 83
learning_rate:
  value: 0.01820104860992966
size_1:
  value: 95
size_2:
  value: 171
size_3:
  value: 183
size_4:
  value: 98
size_5:
  value: 243
