wandb_version: 1

batch_size:
  value: 128
dropout:
  value: 0.29329013762957873
epochs:
  value: 98
learning_rate:
  value: 0.01163987568025774
size_1:
  value: 241
size_2:
  value: 157
size_3:
  value: 119
size_4:
  value: 238
size_5:
  value: 204
