wandb_version: 1

batch_size:
  value: 128
dropout:
  value: 0.21798999550026
epochs:
  value: 54
learning_rate:
  value: 0.09159415984248676
size_1:
  value: 147
size_2:
  value: 86
size_3:
  value: 230
size_4:
  value: 78
size_5:
  value: 115
