wandb_version: 1

batch_size:
  value: 32
dropout:
  value: 0.28689169051128594
epochs:
  value: 38
learning_rate:
  value: 0.011731546890345746
size_1:
  value: 117
size_2:
  value: 214
size_3:
  value: 212
size_4:
  value: 150
size_5:
  value: 126
