wandb_version: 1

batch_size:
  value: 64
dropout:
  value: 0.4169094250554108
epochs:
  value: 77
learning_rate:
  value: 0.03422459031667951
size_1:
  value: 94
size_2:
  value: 94
size_3:
  value: 215
size_4:
  value: 186
size_5:
  value: 161
