wandb_version: 1

batch_size:
  value: 128
dropout:
  value: 0.3553872839982336
epochs:
  value: 74
learning_rate:
  value: 0.045917776622398
size_1:
  value: 178
size_2:
  value: 171
size_3:
  value: 213
size_4:
  value: 82
size_5:
  value: 232
