wandb_version: 1

batch_size:
  value: 96
dropout:
  value: 0.1740940877345769
epochs:
  value: 80
learning_rate:
  value: 0.07813452249817666
size_1:
  value: 153
size_2:
  value: 180
size_3:
  value: 205
size_4:
  value: 212
size_5:
  value: 208
