wandb_version: 1

batch_size:
  value: 128
dropout:
  value: 0.0440928231270973
epochs:
  value: 41
learning_rate:
  value: 0.03757441018799416
size_1:
  value: 106
size_2:
  value: 89
size_3:
  value: 86
size_4:
  value: 119
size_5:
  value: 126
