wandb_version: 1

batch_size:
  value: 64
dropout:
  value: 0.5637498650294573
epochs:
  value: 53
learning_rate:
  value: 0.05854011594612496
size_1:
  value: 90
size_2:
  value: 212
size_3:
  value: 95
size_4:
  value: 245
size_5:
  value: 155
