wandb_version: 1

batch_size:
  value: 32
dropout:
  value: 0.2110360446677748
epochs:
  value: 74
learning_rate:
  value: 0.06478427144180464
size_1:
  value: 211
size_2:
  value: 154
size_3:
  value: 245
size_4:
  value: 94
size_5:
  value: 226
