wandb_version: 1

batch_size:
  value: 128
dropout:
  value: 0.4789036025147468
epochs:
  value: 57
learning_rate:
  value: 0.06426150614583769
size_1:
  value: 103
size_2:
  value: 192
size_3:
  value: 86
size_4:
  value: 171
size_5:
  value: 138
