wandb_version: 1

batch_size:
  value: 64
dropout:
  value: 0.326572767761558
epochs:
  value: 33
learning_rate:
  value: 0.0630521529009863
size_1:
  value: 144
size_2:
  value: 242
size_3:
  value: 101
size_4:
  value: 166
size_5:
  value: 130
