wandb_version: 1

batch_size:
  value: 64
dropout:
  value: 0.13448093132227368
epochs:
  value: 38
learning_rate:
  value: 0.001599630672571495
size_1:
  value: 178
size_2:
  value: 87
size_3:
  value: 209
size_4:
  value: 194
size_5:
  value: 200
