wandb_version: 1

batch_size:
  value: 96
dropout:
  value: 0.08501412971688302
epochs:
  value: 89
learning_rate:
  value: 0.05653185881350084
size_1:
  value: 90
size_2:
  value: 181
size_3:
  value: 87
size_4:
  value: 154
size_5:
  value: 177
