wandb_version: 1

batch_size:
  value: 32
dropout:
  value: 0.5275721039103399
epochs:
  value: 87
learning_rate:
  value: 0.0601393446643601
size_1:
  value: 101
size_2:
  value: 197
size_3:
  value: 164
size_4:
  value: 137
size_5:
  value: 242
