wandb_version: 1

batch_size:
  value: 64
dropout:
  value: 0.22033117920924797
epochs:
  value: 51
learning_rate:
  value: 0.03867890875781595
size_1:
  value: 178
size_2:
  value: 217
size_3:
  value: 187
size_4:
  value: 90
size_5:
  value: 80
