wandb_version: 1

batch_size:
  value: 128
dropout:
  value: 0.1563731510612403
epochs:
  value: 27
learning_rate:
  value: 0.046679883069579875
size_1:
  value: 187
size_2:
  value: 72
size_3:
  value: 102
size_4:
  value: 64
size_5:
  value: 236
