wandb_version: 1

batch_size:
  value: 96
dropout:
  value: 0.2700558617338092
epochs:
  value: 43
learning_rate:
  value: 0.05212524308892931
size_1:
  value: 178
size_2:
  value: 192
size_3:
  value: 102
size_4:
  value: 238
size_5:
  value: 167
