wandb_version: 1

batch_size:
  value: 96
dropout:
  value: 0.042092677552453515
epochs:
  value: 52
learning_rate:
  value: 0.017078192895493605
size_1:
  value: 153
size_2:
  value: 207
size_3:
  value: 69
size_4:
  value: 77
size_5:
  value: 242
