wandb_version: 1

batch_size:
  value: 96
dropout:
  value: 0.4114091212354859
epochs:
  value: 44
learning_rate:
  value: 0.032468829124221076
size_1:
  value: 117
size_2:
  value: 75
size_3:
  value: 240
size_4:
  value: 134
size_5:
  value: 95
