wandb_version: 1

batch_size:
  value: 128
dropout:
  value: 0.29971472974708313
epochs:
  value: 92
learning_rate:
  value: 0.06577280830998228
size_1:
  value: 169
size_2:
  value: 75
size_3:
  value: 74
size_4:
  value: 140
size_5:
  value: 244
