wandb_version: 1

batch_size:
  value: 96
dropout:
  value: 0.12406113648898376
epochs:
  value: 91
learning_rate:
  value: 0.0948014443735528
size_1:
  value: 73
size_2:
  value: 152
size_3:
  value: 115
size_4:
  value: 80
size_5:
  value: 169
