wandb_version: 1

batch_size:
  value: 64
dropout:
  value: 0.2994415608910723
epochs:
  value: 65
learning_rate:
  value: 0.018993144600271274
size_1:
  value: 90
size_2:
  value: 202
size_3:
  value: 171
size_4:
  value: 233
size_5:
  value: 139
