wandb_version: 1

batch_size:
  value: 128
dropout:
  value: 0.5951274739327591
epochs:
  value: 22
learning_rate:
  value: 0.019388922232122265
size_1:
  value: 185
size_2:
  value: 216
size_3:
  value: 154
size_4:
  value: 238
size_5:
  value: 83
