wandb_version: 1

batch_size:
  value: 96
dropout:
  value: 0.26942475712861064
epochs:
  value: 35
learning_rate:
  value: 0.09038198091658298
size_1:
  value: 249
size_2:
  value: 221
size_3:
  value: 221
size_4:
  value: 229
size_5:
  value: 206
