wandb_version: 1

batch_size:
  value: 128
dropout:
  value: 0.5027489451979701
epochs:
  value: 70
learning_rate:
  value: 0.016128828543729812
size_1:
  value: 249
size_2:
  value: 87
size_3:
  value: 244
size_4:
  value: 163
size_5:
  value: 230
