wandb_version: 1

batch_size:
  value: 96
dropout:
  value: 0.1886337325733656
epochs:
  value: 41
learning_rate:
  value: 0.04671489595440448
size_1:
  value: 238
size_2:
  value: 182
size_3:
  value: 209
size_4:
  value: 162
size_5:
  value: 73
