wandb_version: 1

batch_size:
  value: 128
dropout:
  value: 0.02852155927740965
epochs:
  value: 56
learning_rate:
  value: 0.0948918947764631
size_1:
  value: 253
size_2:
  value: 100
size_3:
  value: 181
size_4:
  value: 98
size_5:
  value: 132
