wandb_version: 1

batch_size:
  value: 64
dropout:
  value: 0.38644248746476817
epochs:
  value: 61
learning_rate:
  value: 0.022722558011026184
size_1:
  value: 163
size_2:
  value: 145
size_3:
  value: 118
size_4:
  value: 155
size_5:
  value: 130
