wandb_version: 1

batch_size:
  value: 96
dropout:
  value: 0.5856833965379119
epochs:
  value: 77
learning_rate:
  value: 0.07357526546896133
size_1:
  value: 114
size_2:
  value: 79
size_3:
  value: 213
size_4:
  value: 141
size_5:
  value: 251
