wandb_version: 1

batch_size:
  value: 128
dropout:
  value: 0.10740354936585206
epochs:
  value: 69
learning_rate:
  value: 0.06390101770910654
size_1:
  value: 204
size_2:
  value: 183
size_3:
  value: 245
size_4:
  value: 100
size_5:
  value: 237
