wandb_version: 1

batch_size:
  value: 64
dropout:
  value: 0.34821398316116386
epochs:
  value: 78
learning_rate:
  value: 0.04535263701987673
size_1:
  value: 153
size_2:
  value: 100
size_3:
  value: 96
size_4:
  value: 153
size_5:
  value: 89
