wandb_version: 1

batch_size:
  value: 32
dropout:
  value: 0.41042522005121457
epochs:
  value: 67
learning_rate:
  value: 0.001725683763915542
size_1:
  value: 244
size_2:
  value: 71
size_3:
  value: 89
size_4:
  value: 202
size_5:
  value: 162
