wandb_version: 1

batch_size:
  value: 32
dropout:
  value: 0.4608814547568595
epochs:
  value: 48
learning_rate:
  value: 0.06332434760719935
size_1:
  value: 144
size_2:
  value: 166
size_3:
  value: 157
size_4:
  value: 236
size_5:
  value: 144
