wandb_version: 1

batch_size:
  value: 64
dropout:
  value: 0.4406250175804713
epochs:
  value: 62
learning_rate:
  value: 0.005068541295890572
size_1:
  value: 191
size_2:
  value: 189
size_3:
  value: 88
size_4:
  value: 163
size_5:
  value: 87
