wandb_version: 1

batch_size:
  value: 64
dropout:
  value: 0.5872788371597887
epochs:
  value: 33
learning_rate:
  value: 0.09224258536532624
size_1:
  value: 186
size_2:
  value: 87
size_3:
  value: 248
size_4:
  value: 135
size_5:
  value: 179
