wandb_version: 1

batch_size:
  value: 64
dropout:
  value: 0.5202895969862006
epochs:
  value: 36
learning_rate:
  value: 0.08391067602792977
size_1:
  value: 194
size_2:
  value: 167
size_3:
  value: 145
size_4:
  value: 202
size_5:
  value: 156
