wandb_version: 1

batch_size:
  value: 32
dropout:
  value: 0.06382995818100769
epochs:
  value: 55
learning_rate:
  value: 0.0955393874846632
size_1:
  value: 181
size_2:
  value: 135
size_3:
  value: 200
size_4:
  value: 111
size_5:
  value: 120
