wandb_version: 1

batch_size:
  value: 96
dropout:
  value: 0.30969014214573504
epochs:
  value: 53
learning_rate:
  value: 0.0896116504820449
size_1:
  value: 76
size_2:
  value: 152
size_3:
  value: 176
size_4:
  value: 235
size_5:
  value: 132
