wandb_version: 1

batch_size:
  value: 128
dropout:
  value: 0.02303398085966164
epochs:
  value: 93
learning_rate:
  value: 0.07404084312483625
size_1:
  value: 78
size_2:
  value: 143
size_3:
  value: 112
size_4:
  value: 143
size_5:
  value: 238
