wandb_version: 1

batch_size:
  value: 64
dropout:
  value: 0.32096321432110836
epochs:
  value: 37
learning_rate:
  value: 0.029174512332356628
size_1:
  value: 87
size_2:
  value: 119
size_3:
  value: 124
size_4:
  value: 150
size_5:
  value: 199
