wandb_version: 1

batch_size:
  value: 64
dropout:
  value: 0.2823285847987715
epochs:
  value: 51
learning_rate:
  value: 0.008659294529462248
size_1:
  value: 247
size_2:
  value: 189
size_3:
  value: 87
size_4:
  value: 75
size_5:
  value: 111
