wandb_version: 1

batch_size:
  value: 96
dropout:
  value: 0.5294109874278685
epochs:
  value: 50
learning_rate:
  value: 0.05303855960596382
size_1:
  value: 235
size_2:
  value: 72
size_3:
  value: 138
size_4:
  value: 211
size_5:
  value: 94
