wandb_version: 1

batch_size:
  value: 32
dropout:
  value: 0.27483191756932
epochs:
  value: 57
learning_rate:
  value: 0.08944736530837008
size_1:
  value: 245
size_2:
  value: 176
size_3:
  value: 218
size_4:
  value: 116
size_5:
  value: 81
