wandb_version: 1

batch_size:
  value: 96
dropout:
  value: 0.13146222242369965
epochs:
  value: 56
learning_rate:
  value: 0.02681174938738099
size_1:
  value: 131
size_2:
  value: 240
size_3:
  value: 195
size_4:
  value: 230
size_5:
  value: 119
