wandb_version: 1

batch_size:
  value: 64
dropout:
  value: 0.21069936834034103
epochs:
  value: 96
learning_rate:
  value: 0.06685203359378906
size_1:
  value: 122
size_2:
  value: 215
size_3:
  value: 221
size_4:
  value: 215
size_5:
  value: 229
