wandb_version: 1

batch_size:
  value: 128
dropout:
  value: 0.540451085517444
epochs:
  value: 38
learning_rate:
  value: 0.056633043528705566
size_1:
  value: 84
size_2:
  value: 116
size_3:
  value: 133
size_4:
  value: 205
size_5:
  value: 85
