wandb_version: 1

batch_size:
  value: 96
dropout:
  value: 0.4491906281405757
epochs:
  value: 96
learning_rate:
  value: 0.0037983055979038177
size_1:
  value: 139
size_2:
  value: 212
size_3:
  value: 233
size_4:
  value: 203
size_5:
  value: 103
