wandb_version: 1

batch_size:
  value: 96
dropout:
  value: 0.06861894476520189
epochs:
  value: 62
learning_rate:
  value: 0.04940051950419144
size_1:
  value: 154
size_2:
  value: 225
size_3:
  value: 99
size_4:
  value: 223
size_5:
  value: 188
