wandb_version: 1

batch_size:
  value: 96
dropout:
  value: 0.2752143467664206
epochs:
  value: 69
learning_rate:
  value: 0.019556004168072707
size_1:
  value: 213
size_2:
  value: 95
size_3:
  value: 67
size_4:
  value: 64
size_5:
  value: 168
