wandb_version: 1

batch_size:
  value: 32
dropout:
  value: 0.5792621728827462
epochs:
  value: 74
learning_rate:
  value: 0.03448595616719846
size_1:
  value: 143
size_2:
  value: 251
size_3:
  value: 194
size_4:
  value: 74
size_5:
  value: 105
