wandb_version: 1

batch_size:
  value: 64
dropout:
  value: 0.5331258289950607
epochs:
  value: 79
learning_rate:
  value: 0.015767628796907664
size_1:
  value: 147
size_2:
  value: 176
size_3:
  value: 167
size_4:
  value: 171
size_5:
  value: 65
