wandb_version: 1

batch_size:
  value: 64
dropout:
  value: 0.21086763827743796
epochs:
  value: 85
learning_rate:
  value: 0.03447637863729326
size_1:
  value: 217
size_2:
  value: 128
size_3:
  value: 101
size_4:
  value: 198
size_5:
  value: 94
