wandb_version: 1

batch_size:
  value: 64
dropout:
  value: 0.5990684384704583
epochs:
  value: 69
learning_rate:
  value: 0.026840306526142055
size_1:
  value: 125
size_2:
  value: 176
size_3:
  value: 210
size_4:
  value: 77
size_5:
  value: 208
