wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.5
    framework: keras
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.9.13
    start_time: 1668791013.833876
    t:
      1:
      - 2
      - 3
      - 55
      2:
      - 2
      - 3
      - 55
      3:
      - 2
      - 3
      - 8
      - 23
      - 37
      4: 3.9.13
      5: 0.13.5
      8:
      - 1
      - 5
      10:
      - 9
batch_size:
  desc: null
  value: 96
dropout:
  desc: null
  value: 0.03441949713983043
epochs:
  desc: null
  value: 50
learning_rate:
  desc: null
  value: 0.02451161819510761
size_1:
  desc: null
  value: 79
size_2:
  desc: null
  value: 136
size_3:
  desc: null
  value: 110
size_4:
  desc: null
  value: 252
size_5:
  desc: null
  value: 191
