wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.5
    framework: keras
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.9.13
    start_time: 1668797105.072922
    t:
      1:
      - 2
      - 3
      - 55
      2:
      - 2
      - 3
      - 55
      3:
      - 2
      - 3
      - 8
      - 23
      - 37
      4: 3.9.13
      5: 0.13.5
      8:
      - 1
      - 5
      10:
      - 9
batch_size:
  desc: null
  value: 64
dropout:
  desc: null
  value: 0.25198327632875084
epochs:
  desc: null
  value: 66
learning_rate:
  desc: null
  value: 0.06222180068151413
size_1:
  desc: null
  value: 215
size_2:
  desc: null
  value: 195
size_3:
  desc: null
  value: 243
size_4:
  desc: null
  value: 203
size_5:
  desc: null
  value: 140
