wandb_version: 1

batch_size:
  value: 218
dropout:
  value: 0.10371647600862992
epochs:
  value: 19
learning_rate:
  value: 0.09728279286646528
size_1:
  value: 235
size_2:
  value: 140
size_3:
  value: 77
size_4:
  value: 101
size_5:
  value: 225
