wandb_version: 1

batch_size:
  value: 78
dropout:
  value: 0.32338544783612844
epochs:
  value: 15
learning_rate:
  value: 0.07650238450160682
size_1:
  value: 74
size_2:
  value: 156
size_3:
  value: 99
size_4:
  value: 216
size_5:
  value: 97
