wandb_version: 1

batch_size:
  value: 66
dropout:
  value: 0.3605842120333785
epochs:
  value: 11
learning_rate:
  value: 0.05844537588718618
size_1:
  value: 122
size_2:
  value: 67
size_3:
  value: 147
size_4:
  value: 79
size_5:
  value: 199
