wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.5
    framework: keras
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.9.13
    start_time: 1668670103.281163
    t:
      1:
      - 2
      - 3
      - 55
      2:
      - 2
      - 3
      - 55
      3:
      - 2
      - 3
      - 8
      - 23
      - 37
      4: 3.9.13
      5: 0.13.5
      8:
      - 1
      - 5
      10:
      - 9
batch_size:
  desc: null
  value: 32
dropout:
  desc: null
  value: 0.5985208601091424
epochs:
  desc: null
  value: 92
learning_rate:
  desc: null
  value: 0.059768440183992105
size_1:
  desc: null
  value: 200
size_2:
  desc: null
  value: 252
size_3:
  desc: null
  value: 202
size_4:
  desc: null
  value: 228
size_5:
  desc: null
  value: 127
