wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.5
    framework: keras
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.9.13
    start_time: 1668667268.522982
    t:
      1:
      - 2
      - 3
      - 55
      2:
      - 2
      - 3
      - 55
      3:
      - 2
      - 3
      - 8
      - 23
      - 37
      4: 3.9.13
      5: 0.13.5
      8:
      - 1
      - 5
      10:
      - 9
batch_size:
  desc: null
  value: 32
dropout:
  desc: null
  value: 0.17796450183269555
epochs:
  desc: null
  value: 62
learning_rate:
  desc: null
  value: 0.06818902958648401
size_1:
  desc: null
  value: 124
size_2:
  desc: null
  value: 231
size_3:
  desc: null
  value: 205
size_4:
  desc: null
  value: 91
size_5:
  desc: null
  value: 202
