wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.5
    framework: keras
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.9.13
    start_time: 1668682214.650545
    t:
      1:
      - 2
      - 3
      - 55
      2:
      - 2
      - 3
      - 55
      3:
      - 2
      - 3
      - 8
      - 23
      - 37
      4: 3.9.13
      5: 0.13.5
      8:
      - 1
      - 5
      10:
      - 9
batch_size:
  desc: null
  value: 128
dropout:
  desc: null
  value: 0.04984564303045256
epochs:
  desc: null
  value: 27
learning_rate:
  desc: null
  value: 0.0025120051443257465
size_1:
  desc: null
  value: 174
size_2:
  desc: null
  value: 171
size_3:
  desc: null
  value: 178
size_4:
  desc: null
  value: 180
size_5:
  desc: null
  value: 114
