wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.5
    framework: keras
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.9.13
    start_time: 1668787882.060672
    t:
      1:
      - 2
      - 3
      - 55
      2:
      - 2
      - 3
      - 55
      3:
      - 2
      - 3
      - 8
      - 23
      - 37
      4: 3.9.13
      5: 0.13.5
      8:
      - 1
      - 5
      10:
      - 9
batch_size:
  desc: null
  value: 32
dropout:
  desc: null
  value: 0.27887123976407213
epochs:
  desc: null
  value: 64
learning_rate:
  desc: null
  value: 0.08969830226094197
size_1:
  desc: null
  value: 226
size_2:
  desc: null
  value: 64
size_3:
  desc: null
  value: 148
size_4:
  desc: null
  value: 214
size_5:
  desc: null
  value: 132
