wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.5
    framework: keras
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.9.13
    start_time: 1668668714.752366
    t:
      1:
      - 2
      - 3
      - 55
      2:
      - 2
      - 3
      - 55
      3:
      - 2
      - 3
      - 8
      - 23
      - 37
      4: 3.9.13
      5: 0.13.5
      8:
      - 1
      - 5
      10:
      - 9
batch_size:
  desc: null
  value: 32
dropout:
  desc: null
  value: 0.39977722371751007
epochs:
  desc: null
  value: 95
learning_rate:
  desc: null
  value: 0.05476650572814632
size_1:
  desc: null
  value: 147
size_2:
  desc: null
  value: 97
size_3:
  desc: null
  value: 141
size_4:
  desc: null
  value: 182
size_5:
  desc: null
  value: 203
