wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.5
    framework: keras
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.9.13
    start_time: 1668779513.913362
    t:
      1:
      - 2
      - 3
      - 55
      2:
      - 2
      - 3
      - 55
      3:
      - 2
      - 3
      - 8
      - 23
      - 37
      4: 3.9.13
      5: 0.13.5
      8:
      - 1
      - 5
      10:
      - 9
batch_size:
  desc: null
  value: 96
dropout:
  desc: null
  value: 0.5294109874278685
epochs:
  desc: null
  value: 50
learning_rate:
  desc: null
  value: 0.05303855960596382
size_1:
  desc: null
  value: 235
size_2:
  desc: null
  value: 72
size_3:
  desc: null
  value: 138
size_4:
  desc: null
  value: 211
size_5:
  desc: null
  value: 94
