wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.5
    framework: keras
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.9.13
    start_time: 1668674410.554539
    t:
      1:
      - 2
      - 3
      - 55
      2:
      - 2
      - 3
      - 55
      3:
      - 2
      - 3
      - 8
      - 23
      - 37
      4: 3.9.13
      5: 0.13.5
      8:
      - 1
      - 5
      10:
      - 9
batch_size:
  desc: null
  value: 32
dropout:
  desc: null
  value: 0.5100580029396404
epochs:
  desc: null
  value: 74
learning_rate:
  desc: null
  value: 0.07783788491965006
size_1:
  desc: null
  value: 138
size_2:
  desc: null
  value: 84
size_3:
  desc: null
  value: 135
size_4:
  desc: null
  value: 145
size_5:
  desc: null
  value: 225
