wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.5
    framework: keras
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.9.13
    start_time: 1668685559.371267
    t:
      1:
      - 2
      - 3
      - 55
      2:
      - 2
      - 3
      - 55
      3:
      - 2
      - 3
      - 8
      - 23
      - 37
      4: 3.9.13
      5: 0.13.5
      8:
      - 1
      - 5
      10:
      - 9
batch_size:
  desc: null
  value: 32
dropout:
  desc: null
  value: 0.2664278885271979
epochs:
  desc: null
  value: 90
learning_rate:
  desc: null
  value: 0.0858561785095313
size_1:
  desc: null
  value: 194
size_2:
  desc: null
  value: 140
size_3:
  desc: null
  value: 221
size_4:
  desc: null
  value: 66
size_5:
  desc: null
  value: 119
