wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.5
    framework: keras
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.9.13
    start_time: 1668790875.52627
    t:
      1:
      - 2
      - 3
      - 55
      2:
      - 2
      - 3
      - 55
      3:
      - 2
      - 3
      - 8
      - 23
      - 37
      4: 3.9.13
      5: 0.13.5
      8:
      - 1
      - 5
      10:
      - 9
batch_size:
  desc: null
  value: 64
dropout:
  desc: null
  value: 0.5202895969862006
epochs:
  desc: null
  value: 36
learning_rate:
  desc: null
  value: 0.08391067602792977
size_1:
  desc: null
  value: 194
size_2:
  desc: null
  value: 167
size_3:
  desc: null
  value: 145
size_4:
  desc: null
  value: 202
size_5:
  desc: null
  value: 156
