wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.5
    framework: keras
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.9.13
    start_time: 1668776560.607474
    t:
      1:
      - 2
      - 3
      - 55
      2:
      - 2
      - 3
      - 55
      3:
      - 2
      - 3
      - 8
      - 23
      - 37
      4: 3.9.13
      5: 0.13.5
      8:
      - 1
      - 5
      10:
      - 9
batch_size:
  desc: null
  value: 96
dropout:
  desc: null
  value: 0.5709814724183551
epochs:
  desc: null
  value: 45
learning_rate:
  desc: null
  value: 0.05909337755842904
size_1:
  desc: null
  value: 194
size_2:
  desc: null
  value: 129
size_3:
  desc: null
  value: 256
size_4:
  desc: null
  value: 162
size_5:
  desc: null
  value: 145
