wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.5
    framework: keras
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.9.13
    start_time: 1668792121.785943
    t:
      1:
      - 2
      - 3
      - 55
      2:
      - 2
      - 3
      - 55
      3:
      - 2
      - 3
      - 8
      - 23
      - 37
      4: 3.9.13
      5: 0.13.5
      8:
      - 1
      - 5
      10:
      - 9
batch_size:
  desc: null
  value: 128
dropout:
  desc: null
  value: 0.012085155391357547
epochs:
  desc: null
  value: 69
learning_rate:
  desc: null
  value: 0.0702146982943237
size_1:
  desc: null
  value: 108
size_2:
  desc: null
  value: 147
size_3:
  desc: null
  value: 152
size_4:
  desc: null
  value: 197
size_5:
  desc: null
  value: 126
