wandb_version: 1

batch_size:
  value: 141
dropout:
  value: 0.2862021717075106
epochs:
  value: 13
learning_rate:
  value: 0.09334165953724564
size_1:
  value: 184
size_2:
  value: 160
size_3:
  value: 136
size_4:
  value: 175
size_5:
  value: 192
