wandb_version: 1

batch_size:
  value: 111
dropout:
  value: 0.522688875081156
epochs:
  value: 19
learning_rate:
  value: 0.0895242500569196
size_1:
  value: 134
size_2:
  value: 250
size_3:
  value: 216
size_4:
  value: 255
size_5:
  value: 94
