wandb_version: 1

batch_size:
  value: 115
dropout:
  value: 0.2076361870988395
epochs:
  value: 18
learning_rate:
  value: 0.04223573087570981
size_1:
  value: 208
size_2:
  value: 79
size_3:
  value: 160
size_4:
  value: 163
size_5:
  value: 163
