wandb_version: 1

batch_size:
  value: 203
dropout:
  value: 0.15374186431947892
epochs:
  value: 19
learning_rate:
  value: 0.04759324204500605
size_1:
  value: 175
size_2:
  value: 84
size_3:
  value: 101
size_4:
  value: 172
size_5:
  value: 130
