wandb_version: 1

batch_size:
  value: 145
dropout:
  value: 0.11571657331598544
epochs:
  value: 19
learning_rate:
  value: 0.04638240373431901
size_1:
  value: 219
size_2:
  value: 90
size_3:
  value: 96
size_4:
  value: 227
size_5:
  value: 142
